export const Spanish = {
  //herosection
  heroTitle: "Un instituto de idiomas profesional, personalizado y flexible",
  heroSubtitle:"¿Te gustaría aprender un idioma? Toma clases con nosotros y no solo aprenderás practicando con un profesor nativo, sino que también puedes crear tu propio curso personalizado según tus necesidades.",
  heroSubtitletwo:"Ofrecemos clases en estos idiomas: Inglés, Francés, Alemán, Portugués, Italiano, Chino, Español para extranjeros",
  buttonMoreInfo: "Más info",

  //navbar
  navAboutus: "Acerca de nosotros",
  navClasses: "Clases",
  navTranslations: "Traducciones",
  navGroups: "Grupos",
  navPrices: "Paquetes",
  navReviews: "Opiniones",
  navContact: "Contacto",
  navLanguage: "Idioma",

  //aboutus
  aboutusTitle: "Aprende un nuevo idioma desde cualquier parte del mundo",
  aboutusParagraphOne:"Robinson's Institute of Languages se fundó en 2011 con la intención de ofrecer clases de idioma para personas que buscan aprender de una manera personalizada en la ciudad de Buenos Aires.",
  aboutusParagraphTwo:"Nos especializamos en clases para estudiantes que quieran dar exámenes, ir de viaje, hacer negocios o solo aprender un idioma en general.",
  aboutusParagraphThree:"Todos los profesores en el instituto son expertos en el idioma y cuentan con certificaciones de enseñanza tanto como experiencia dictando clases. Además contamos con una variedad de profesores nativos.",
  aboutusParagraphFour: "El departamento de traducciones se abrió en 2013 y consiste de ambos traductores públicos argentinos y traductores nativos del inglés para lograr mejores traducciones. Trabajamos en equipo para poder traducir largos textos en menos tiempo sin perder la calidad de la traducción.",

  //  classes
  classesTitle: "Logra más con RIL",
  classesVirtual: "Clases virtuales",
  classesParagraphOne:"En Robinson's Institute of Languages sabemos la importancia que tiene la conversación a la hora de aprender un idioma nuevo. Es por eso que nuestra forma de enseñar se basa en la conversación. Todos los profesores cuentan con certificaciones internacionales y experiencia en la enseñanza. La mayoría de los profesores son nativos, pero también hay profesores locales que vivieron en el exterior por un tiempo y que puedan explicar las reglas en castellano si es que el estudiante lo requiere. Somos expertos en evaluar el nivel y las necesidades de cada alumno para planificar un curso personalizado.",

  classesGroupAndIndividual: "Clases individuales y grupales",
  classesParagraph:"Desbloquea el poder de tu camino personalizado de aprendizaje para lograr tus objetivo de idioma rapido. ¡Descubre cuán fácil y divertido puede ser aprender un nuevo idioma con Robinson Institute of Language!",
  classesParagraphTwo: "Buscamos crear clases dinámicas e interactivas. Usamos diferentes herramientas, como el internet, para hacer de las clases más divertidas y completas. Contamos con material gramatical, actividades de escuchar y leer y para preparación de exámenes.",
  classesParagraphThree:"Ofrecemos flexibilidad en cuanto al horario y lugar donde se toman las clases. Se puede tomar clases individuales o en grupo.",

  //translations
  translationsTitle: "Servicios de traducciones",
  translationButton:"Ver más sobre nuestros servicios de traducciones",
  translationOrangeBgTitle: "¿Tienes más preguntas?",
  translationOrangeBgSubtitle: "¡Contactanos!",
  translationOrangeBgParagraphOne: "Nuestro equipo está preparado para encontrar una solución a",
  translationOrangeBgParagraphTwo: "tus necesidades de traducción",
  translationOrangeBgButton: "Contactános",
  translationsParagraphOne:
    "Nuestro servicio de traducción e interpretación son profesionales. Contamos con traductores públicos de Argentina y traductores nativos del Reino Unido y Estados Unidos. Trabajamos juntos para lograr una mejor traducción.",

  //translationPublic
  translationsPublic: "Traducciones Públicas",
  translationsPublicBold: "Por documentos como:",
  translationsPublicListOne: "Certificados de nacimiento, defunción, matrimonio y divorcio",
  translationsPublicListTwo: "Pasaportes y demás documentos personales",
  translationsPublicListThree: "Testamentos",
  translationsPublicListFour:"Programas de estudios, certificados analíticos, diplomas, CV, y demás documentos relacionados con la educación",
  translationsPublicListFive: "Poderes",
  translationsPublicListSix:"Documentos Societarios (actas constitutivas, estatutos societarios, actas de asamblea y de directorio, documentos comerciales, y otros documentos societarios)",
  translationsPublicListSeven: "Documentos técnicos y científicos",
  translationsPublicListEight:"Patentes de invención, propiedad intelectual, derechos de autor",
  translationsPublicListNine: "Estados contables",

  //translationPrivate
  translationsPrivate: "Traducciones Privadas",
  translationsPrivateBold: "Por documentos en las áreas de:",
  translationsPrivateListOne: "Economía y Finanzas",
  translationsPrivateListTwo: "Comerciales",
  translationsPrivateListThree: "Técnicas",
  translationsPrivateListFour: "Literarias",
  translationsPrivateListFive: "Artículos periodísticos",
  translationsPrivateListSix: "Tesis",
  translationsPrivateListSeven: "Presentaciones",

  //translationInterpretation
  translationsInterpretation: "Interpretación",
  translationsInterpretationBold: "Para dar asistencia idiomática:",
  translationsInterpretationListOne: "En congresos y conferencias",
  translationsInterpretationListTwo: "En reuniones de negocios",
  translationsInterpretationListThree: "A visitantes extranjeros",

  //groups
  groupsTitle: "Grupos",
  groupsButton: "Buscar un grupo",
  

    //prices
    pricesError: "por favor, seleccione 1 mes o 3 meses",
    pricesTitle: "Mira nuestros planes",
    starterTitle: "Starter",
    starterSubtitle: "1 hora por semana",
    starterSubtitleTwo: "1 clase por semana",
    starterText: "Mantiene contacto con el idioma, evite perder su nivel",
    starterPriceDollarsMonth: "USD $60",
    starterPricePesosMonth: "ARS $19.200",
    starterPriceDollarsMonthGroup: "USD $32",
    starterPricePesosMonthGroup: "ARS $10.000",
    starterPriceDollarsThreeMonths: "USD $162",
    starterPricePesosThreeMonths: "ARS $51.840",
    starterPriceDollarsThreeMonthsGroup: "USD $86.4",
    starterPricePesosThreeMonthsGroup: "ARS $27.000",
    semiProTitle: "Semi-pro",
    semiProSubtitle: "2 horas por semana",
    semiProSubtitleTwo: "2 clases por semana",
    semiProPriceDollarsMonth: "USD $116",
    semiProPricePesosMonth: "ARS $36.800",
    semiProPriceDollarsMonthGroup: "USD $60",
    semiProPricePesosMonthGroup: "ARS $19.200",
    semiProPriceDollarsThreeMonths: "USD $312.2",
    semiProPricePesosThreeMonths: "ARS $99.360",
    semiProPriceDollarsThreeMonthsGroup: "USD $162",
    semiProPricePesosThreeMonthsGroup: "ARS $51.840",
    semiProText: "Mejore su nivel del idioma aprendiendo nueva gramática y vocabulario",
    proTitle: "Pro",
    proSubtitle: "3 horas por semana",
    proSubtitleTwo: "3 clases por semana",
    proPriceDollarsMonth: "USD $168",
    proPricePesosMonth: "ARS $52800",
    proPriceDollarsMonthGroup: "USD $84",
    proPricePesosMonthGroup: "ARS $27.600",
    proPriceDollarsThreeMonths: "USD $453.6",
    proPricePesosThreeMonths: "ARS $142.560",
    proPriceDollarsThreeMonthsGroup: "USD $226.8",
    proPricePesosThreeMonthsGroup: "ARS $74.520",
    proText: "Curso intensivo, usualmente por algo específico, cumpla sus objetivos en un plazo más corto",
    pricesButtonIndividual: "Clases individuales",
    pricesButtonGroup: "Buscar Grupo",
    pricesRenewMonth: "Se renueva todos los meses",
    pricesRenewThreeMonths: "Se renueva todos los años",
    pricesMonth: "1 mes",
    pricesThreeMonths: "3 meses",
    //reviews
    reviewsTitle: "Algunos de nuestros clientes felices",
    companiesThatTrustUs: "Empresas que confían en nosotros",

    //contact
    contactTitle: "Contacto",
    contactName: "Nombre",
    contactEmail: "Email",
    contactTelephone: "Teléfono",
    contactMessage: "Mensaje",
    contactButton: "Enviar",
    placeholderName: "Ingrese su nombre",
    placeholderEmail: "Ingrese su email",
    placeholderTelephone: "Ingrese su teléfono",
    placeholderMessage: "Ingrese su mensaje",


    //form
    formtitle: "Buscar un grupo",
    formtitleIndividual: "Clases individuales",
    modalSuccessForm: "Gracias por llenar su formulario! Uno de nuestro equipo va a estar en contacto pronto con usted.",
    modalWarningGroup: "Ha seleccionado menos de tres horarios. ¿Estás seguro de que quieres continuar?",
    modalWarningIndividual: "Ha seleccionado menos de tres horarios. ¿Estás seguro de que quieres continuar?",
    modalWarningButton: "Sí, estoy seguro",
    modalWarningButtonCancel: "No, quiero seleccionar más horarios",
    modalWarningTitle: "¡Atención!",
    modalSuccess: "Formulario enviado con éxito!",
    formAreSureYouWantToLeave: "¿Estás seguro que quieres salir? Perderás todos los datos que hayas ingresado.",

    //general
    generalBlueButton: "¡Empieza tu programa hoy!",
    placeholderFirstName: "Ingrese su nombre",
    placeholderLastName: "Ingrese su apellido",
    placeholderSelectLanguage: "Seleccione un idioma",
    placeholderSelectLevel: "Seleccione un nivel",
    placeholderSelectObjective: "Seleccione un objetivo",
    placeholderPreferedSchedule: "Seleccione un horario",
    placeholderSelectDay: "Seleccione un día",
    placeholderSelectTime: "Seleccione un horario",
    placeholderExam: "Seleccione un examen",
    placeholderTimeZone: "Seleccione una zona horaria",
    placeholderListPreferedSchedule: "Agregue un horario acá",
    examOtherPleaseSpecify: "Especifique examen",
    buttonSubmit: "Enviar",
    buttonAdd: "Agregar",
    errorFirstName: "Por favor ingrese su nombre",
    errorLastName: "Por favor ingrese su apellido",
    errorTimeZone: "Por favor seleccione primero una zona horaria y luego un horario",
    errorDayorTime: "Por favor seleccione un dia y un horario preferido",
    errorEmail: "Por favor ingrese un email valido",
    errorTelephone: "Por favor ingrese un teléfono valido",
    errorLanguage: "Por favor seleccione un idioma",
    errorLevel: "Por favor seleccione un nivel",
    errorObjective: "Por favor seleccione un objetivo",
    errorSchedule: "Por favor seleccione un horario",
    errorDay: "Por favor seleccione un día",
    errorTelephoneLenght: "Por favor ingrese un teléfono válido",
    errorTime: "Por favor seleccione un horario",
    errorExam: "Por favor seleccione un examen",
    errorFormMessage: "Por favor complete el formulario entero",
    errorSpecifyExam: "Por favor especifique el examen",
    errorInvalidTime: "Por favor seleccione un horario válido",
    errorFormGeneral: "Por favor complete el formulario, que todos los campos estén completos y seleccionados correctamente, y que haya eligido al menos tres horarios",
    placeholderExamSpecific: "Cual examen?",
    alertyoullbecontacted: "Gracias por contactarnos, nos pondremos en contacto con usted a la brevedad",
    buttonClose: "Cerrar",
    alertMessageSent: "Mensaje enviado",

    //languages
    english: "Inglés",
    spanish: "Español para extranjeros",
    french: "Francés",
    german: "Alemán",
    italian: "Italiano",
    portuguese: "Portugués",
    russian: "Ruso",


    //levels
    beginner: "Principiante",
    preIntermediate: "Pre-intermedio",
    intermediate: "Intermedio",
    upperIntermediate: "Superior-intermedio",
    advanced: "Avanzado",

    //objectives
    conversation: "Conversación",
    exam: "Preparación de exámenes",
    business: "Negocios",

    //days
    monday: "Lunes",
    tuesday: "Martes",
    wednesday: "Miércoles",
    thursday: "Jueves",
    friday: "Viernes",
    saturday: "Sábado",
    sunday: "Domingo",

     //footer:
     footerAbout : "Acerca de nosotros",
     footerContact: "Contacto",
     footerFollowUs: "Síguenos",
     footerLanguageCourses: "Cursos de idiomas",
     footerGroupClasses: "Clases en grupo",
     footerTranslationService: "Servicio de traducción",
     footerPackages: "Paquetes",
     footerReviews: "Opiniones"


};
